import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Form from '@/components/Form'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

      </header>
      <main className={`${styles.main}`}>
        <Image src={'/images/xlogo.png'} alt="x logo" width={40} height={40} />
        <div className={`${styles.h1}`}>
          <h1 >Sign in to X</h1>
        </div>
        <Button />
        <hr className={`${styles.hr}`}></hr>
        <span className={`${styles.span}`}>or</span>
        <Form />
        <p className={styles.p}>
          Don't have an account? <Link href="/home">Sign Up</Link>
        </p>
      </main>
      <footer>

      </footer>
    </>
  )
}
